// Noms populaires des objets Messier
const messierNames = {
  "M-001": "Nébuleuse du Crabe",
  "M-002": "Amas Globulaire",
  "M-003": "Amas Globulaire",
  "M-004": "Amas Globulaire",
  "M-005": "Amas Globulaire",
  "M-006": "Amas du Papillon",
  "M-007": "Amas de Ptolémée",
  "M-008": "Nébuleuse de la Lagune",
  "M-009": "Amas Globulaire",
  "M-010": "Amas Globulaire",
  "M-011": "Amas du Canard Sauvage",
  "M-012": "Amas Globulaire",
  "M-013": "Grand Amas d'Hercule",
  "M-014": "Amas Globulaire",
  "M-015": "Amas Globulaire",
  "M-016": "Nébuleuse de l'Aigle",
  "M-017": "Nébuleuse Oméga",
  "M-018": "Amas Ouvert",
  "M-019": "Amas Globulaire",
  "M-020": "Nébuleuse Trifide",
  "M-021": "Amas Ouvert",
  "M-022": "Amas Globulaire",
  "M-023": "Amas Ouvert",
  "M-024": "Nuage Stellaire du Sagittaire",
  "M-025": "Amas Ouvert",
  "M-026": "Amas Ouvert",
  "M-027": "Nébuleuse de l'Haltère",
  "M-028": "Amas Globulaire",
  "M-029": "Amas Ouvert",
  "M-030": "Amas Globulaire",
  "M-031": "Galaxie d'Andromède",
  "M-032": "Galaxie Satellite d'Andromède",
  "M-033": "Galaxie du Triangle",
  "M-034": "Amas Ouvert",
  "M-035": "Amas Ouvert",
  "M-036": "Amas Ouvert",
  "M-037": "Amas Ouvert",
  "M-038": "Amas Ouvert",
  "M-039": "Amas Ouvert",
  "M-040": "Double Étoile",
  "M-041": "Amas Ouvert",
  "M-042": "Grande Nébuleuse d'Orion",
  "M-043": "Nébuleuse de Mairan",
  "M-044": "Amas de la Ruche",
  "M-045": "Pléiades",
  "M-046": "Amas Ouvert",
  "M-047": "Amas Ouvert",
  "M-048": "Amas Ouvert",
  "M-049": "Galaxie Elliptique",
  "M-050": "Amas Ouvert",
  "M-051": "Galaxie du Tourbillon",
  "M-052": "Amas Ouvert",
  "M-053": "Amas Globulaire",
  "M-054": "Amas Globulaire",
  "M-055": "Amas Globulaire",
  "M-056": "Amas Globulaire",
  "M-057": "Nébuleuse de l'Anneau",
  "M-058": "Galaxie Spirale",
  "M-059": "Galaxie Elliptique",
  "M-060": "Galaxie Elliptique",
  "M-061": "Galaxie Spirale",
  "M-062": "Amas Globulaire",
  "M-063": "Galaxie du Tournesol",
  "M-064": "Galaxie de l'Œil Noir",
  "M-065": "Galaxie Spirale",
  "M-066": "Galaxie Spirale",
  "M-067": "Amas Ouvert",
  "M-068": "Amas Globulaire",
  "M-069": "Amas Globulaire",
  "M-070": "Amas Globulaire",
  "M-071": "Amas Globulaire",
  "M-072": "Amas Globulaire",
  "M-073": "Astérisme",
  "M-074": "Galaxie Spirale",
  "M-075": "Amas Globulaire",
  "M-076": "Petite Nébuleuse de l'Haltère",
  "M-077": "Galaxie de Baleine",
  "M-078": "Nébuleuse par Réflexion",
  "M-079": "Amas Globulaire",
  "M-080": "Amas Globulaire",
  "M-081": "Galaxie de Bode",
  "M-082": "Galaxie du Cigare",
  "M-083": "Galaxie du Moulinet Austral",
  "M-084": "Galaxie Lenticulaire",
  "M-085": "Galaxie Lenticulaire",
  "M-086": "Galaxie Elliptique",
  "M-087": "Galaxie de la Vierge",
  "M-088": "Galaxie Spirale",
  "M-089": "Galaxie Elliptique",
  "M-090": "Galaxie Spirale",
  "M-091": "Galaxie Spirale",
  "M-092": "Amas Globulaire",
  "M-093": "Amas Ouvert",
  "M-094": "Galaxie de l'Œil de Chat",
  "M-095": "Galaxie Spirale Barrée",
  "M-096": "Galaxie Spirale",
  "M-097": "Nébuleuse du Hibou",
  "M-098": "Galaxie Spirale",
  "M-099": "Galaxie Spirale",
  "M-100": "Galaxie Spirale",
  "M-101": "Galaxie du Moulinet",
  "M-102": "Galaxie Lenticulaire",
  "M-103": "Amas Ouvert",
  "M-104": "Galaxie du Sombrero",
  "M-105": "Galaxie Elliptique",
  "M-106": "Galaxie Spirale",
  "M-107": "Amas Globulaire",
  "M-108": "Galaxie Spirale",
  "M-109": "Galaxie Spirale Barrée",
  "M-110": "Galaxie Satellite d'Andromède"
};
